### PR TITLE
Tree player interaction

### PR DESCRIPTION
**Pull request by Shermol**

### CODE REVIEW

**Review by chloealbright — COMMENTED** [review]
I resolved your merge conflicts for your branch, please make sure that the updated ItemSO objects and script works with your scene/components. Your changes shouldn't be affected.

**Review by Annie-Mai — CHANGES_REQUESTED** [review]
There seem to be a few issues:
- on the carrot plant you have placed, I checked the timer for when it is supposed to sprout, however as soon as it hits 0 nothing happens, the timer resets to 60
     - because of that I am unable to test to see if the inventory system is working as intended from when we tested it originally
- you need to remove the test inventory you have in the scene because it interferes with the one from the farm inventory 
     
Something to keep in mind: 

- would the timer still work when the player is not in the same scene ( would the plant continue to grow?)

**Comment by Shermol** [comment]
Issues Im still having
- Trying to find a way to keep items within the scene active while in another scene
- Trying to solve issue with disappearing sprites

**Comment by Shermol** [comment]
Problems Addressed:
- Players are able to plant again, plants will need time to grow instead of spawning in fully grown

**Comment by Shermol** [comment]
Problem Addressed:
- Plants would remain even when the player is in a separate scene
Problem Existing:
- Wheat crop Sprites Disappear when harvested but do exit.

Working on:
-Trying to interact with items in inventory in order to track what the player can and cannot plant

**Pull request closed without merging**
