### PR TITLE
Restore dungeon

### PR DESCRIPTION
**Pull request by chloealbright**
Scripts Added:✨
Added Scene Transitions *i.e NextScene script*, NextScene prefab, and Dungeon Vectors to the Dungeon scenes.
Also updated PlayerController script so that the *Sprite position* isn't set to default coordinates (0,0) when a player moves through each scene. The scene transitions are fully functional 

SCENE ORDER 🎞️:
Dungeon Entrance > DLevel1A > DLevel1B > DLevel2A 
> Loops back to the Dungeon Entrance at the next exit of DLevel2A.

NOTE FOR DAN: On the Dungeon Scene Entrance I set the prefab *Dan's BattleRun* for you to add your map to for the scene change. 

Scene fixes: 🔧
I edited the tilemap and tile palette for some Dungeon scenes with lines/spaces on the map during Player Mode. 
I was able to fix most of the glitches, but DLevel1A still has a couple of lines from previous tile splits.  
I think this should be fine for now.

### CODE REVIEW

**Review by Lindanny9721 — CHANGES_REQUESTED** [review]
Just a minor change and question, in the dungeon the Asset Pack is now completely empty so I think you should delete it and there is a CozyFarmAssetPack2 in the dungeon assets. Would you still need that folder since it's already in the asset folder as CozyFarmAnimalPack?

**Review by Annie-Mai — CHANGES_REQUESTED** [review]
There seem to be a few duplicates
image

**Comment by chloealbright** [comment]
> Scripts Added:✨ Added Scene Transitions _i.e NextScene script_, NextScene prefab, and Dungeon Vectors to the Dungeon scenes. Also updated PlayerController script so that the _Sprite position_ isn't set to default coordinates (0,0) when a player moves through each scene. The scene transitions are fully functional
> 
> SCENE ORDER 🎞️: Dungeon Entrance > DLevel1A > DLevel1B > DLevel2A
> 
> > Loops back to the Dungeon Entrance at the next exit of DLevel2A.
> 
> NOTE FOR DAN: On the Dungeon Scene Entrance I set the prefab _Dan's BattleRun_ for you to add your map to for the scene change.
> 
> Scene fixes: 🔧 I edited the tilemap and tile palette for some Dungeon scenes with lines/spaces on the map during Player Mode. I was able to fix most of the glitches, but DLevel1A still has a couple of lines from previous tile splits. I think this should be fine for now.

**Review by LizaFeng — CHANGES_REQUESTED** [review]
corrections have been made and the game works. The user is not able to go to the right side since it would just respawn them back to the same place, but this makes sense since Dan did not add his tile based part yet. I noticed that the user does go off screen before the scene changes though

**Pull request merged**
