### PR TITLE
Tree featurre

### PR DESCRIPTION
**Pull request by Shermol**
Feature: Added the ability to cut down and receive items from trees

### CODE REVIEW

**Review by Annie-Mai — CHANGES_REQUESTED** [review]
The item collections seem to be giving errors, can you please take a look at that/

**Review by Annie-Mai — CHANGES_REQUESTED** [review]
The tree feature looks good, but I believe some of the asset files are not supposed to be added in, please double check them.

**Review by Lindanny9721 — APPROVED** [review]
Looks like it fully works, just got to begin connecting it to the inventory. It does look like there's a slight movement error in the Movement.cs at line 17 for the script in farm but it doesn't really affect it. Just needs a minor change next time.

**Review by LizaFeng — APPROVED** [review]
Looks good to merge

**Comment by chloealbright** [comment]
The tree feature looks good, just check the script Movement.cs:17 script re-Dan's comment for future commits. 
When the tree drops the items they should show up in the same x&y coordinate area that the tree disappears- for future commits. 
All good to merge.

**Review by chloealbright — COMMENTED** [review]
The tree feature looks good, just check the script Movement.cs:17 script re-Dan's comment for future commits.
When the tree drops the items they should show up in the same x&y coordinate area that the tree disappears- for future commits.
*Approved* All good to merge.

**Pull request merged**
