### PR TITLE
Shop Feature Updates

### PR DESCRIPTION
**Pull request by chloealbright**
🔧Shop Feature Updates
✅ Switched the Shop Pop-Up from a keypress 'P' to a Collider pop-up. 
- When the player walks up to the cow-merchant, the shop opens & the shop closes when the player walks away.
- Gold button still generates gold like before for testing. The player balance/sell feature will be implemented next.
- Work In Progress: can't interact with the goldshopUI when Player presses on "Sell Crops" button. Setting game objects to active/inactive hasn't resolved the issue. 
✅  Shop UI connects to inventory when the Player purchases a new item
✅  ShopItems Scriptable Objects are now stackable upon purchase, preview below:
Screenshot 2023-05-09 at 1 26 14 AM

### CODE REVIEW

**Review by Lindanny9721 — CHANGES_REQUESTED** [review]
The generate gold button doesn't work anymore but walking up the cow still works

**Review by LizaFeng — APPROVED** [review]
The shop UI in the barn works well and when the user walks away the shop disappears

**Comment by Shermol** [comment]
The shop ui works fine when approaching the cow

**Review by Lindanny9721 — CHANGES_REQUESTED** [review]
The prices in the seeds changes every time I buy it, sometimes it cost 5 sometime it cost 10 or 15. Also every seed I buy it only gives me carrot seed

**Comment by chloealbright** [comment]
> The prices in the seeds changes every time I buy it, sometimes it cost 5 sometime it cost 10 or 15. Also every seed I buy it only gives me carrot seed

The buttons indexing got mixed somehow but this has been fixed in the most recent commit. 
Note the selling feature is scrollable/but the sell buttons don't work because we need a way to connect to the existing items in inventory. 
Screenshot 2023-05-09 at 1 26 14 AM

**Review by Lindanny9721 — APPROVED** [review]
Looks like it works now!

**Pull request merged**
